# Generated by Django 3.1.2 on 2020-10-03 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tages.countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'Private'), ('company', 'Company'), ('individual_company', 'Individual company'), ('public_administration', 'Public administration'), ('organization', 'Organization')], db_index=True, default='private', max_length=50, verbose_name='type')),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='business name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='last name')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='first name')),
                ('description', models.CharField(db_index=True, default='', editable=False, max_length=200, verbose_name='description')),
                ('customer', models.BooleanField(db_index=True, default=True, verbose_name='customer')),
                ('supplier', models.BooleanField(db_index=True, default=False, verbose_name='supplier')),
                ('vat_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='vat number')),
                ('social_security_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='social security number')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='external id')),
                ('country', tages.countries.fields.CountryField(blank=True, db_index=True, default='GB', max_length=2, verbose_name='country')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='address')),
                ('street_number', models.CharField(blank=True, max_length=50, verbose_name='street number')),
                ('zip_code', models.CharField(blank=True, max_length=50, verbose_name='zip code')),
                ('phone_number', models.CharField(blank=True, max_length=200, verbose_name='phone number')),
                ('fax_number', models.CharField(blank=True, max_length=200, verbose_name='fax number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('pec', models.EmailField(blank=True, max_length=254, verbose_name='pec')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('deactivation_date', models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='deactivation date')),
                ('insert_date', models.DateField(db_index=True, default=datetime.date.today, editable=False, verbose_name='insert date')),
            ],
            options={
                'verbose_name': 'registry',
                'verbose_name_plural': 'registries',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(db_index=True, max_length=200, verbose_name='last name')),
                ('description', models.CharField(db_index=True, default='', editable=False, max_length=200, verbose_name='description')),
                ('parent_1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent_1_childs', to='registries.registry', verbose_name='parent 1')),
                ('parent_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent_2_childs', to='registries.registry', verbose_name='parent 2')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
